language: swift
osx_image: xcode11.3.1
script:
  - xcodebuild -project DarkLightning.xcodeproj -scheme OSX -sdk macosx -enableCodeCoverage YES clean build test
after_success:
- bash <(curl -s https://codecov.io/bash)
